logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
spring:
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath*:initDb/schema.sql
      data-locations: classpath*:initDb/data.sql