springdoc:
  packages-to-scan: com.backend.topcariving.domain
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

token:
  access-token-expiration: ENC(wPeBVsCNvfRyE/b0nLCOoQ==)
  secret-key: ENC(9w2F54pDUxduEsjYPcFteYskKT9NelCfXUUf4KQReW7YjPUi2bq4pYDEn9gOSznpdjYrYr71ceATvazxeaNAGQ==)
  refresh-token-expiration: ENC(mlFa5gn8QYv4oNg7SxvxiA==)


oauth:
  hyundai:
    state: ENC(97DU+WRuZSA0oGnT/N/UnlknLLxShtIM)
    client-id: ENC(Keh7pUQRMKFJ8P4qOU6E7suTjkHP1yNnbVTBtmCAdTsJ1I8rtDYj4/BT91IaXMUB)
    client-secret: ENC(LPEsledj2yz9tkLR4TBlO9pkv+WwylkcWgp2UQE/g65iQ4K8IBPXopfSrEJhlf2Lo73OoElMOmAHHwUUhg2sGQ==)
    redirect-uri: https://www.topcariving.com/oauth-redirect

spring:
  cache:
    type: redis
    redis:
      cache-null-values: true
