spring:
  redis:
    host: ENC(QkIm4Fx0t9RNQtBYzY0/1gTlfOjYGbmA)
    port: ENC(ysB2BXToP07TTsFKCsTknw==)
    password: ENC(UJ9WdLu3WVgjLl+kBE1VMJw1SLQ2B0dX)
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(0SUyw7B+cKv9VCZDbAiYmzMZNVTVmQeh4NQqck4CdcYZBiYd14BQplaUFm+xRZfRYzSKGtsaJfGQjFKPYsCswXb8/K+pwJYz+bLkmWEi410Qs+SxBmqetg==)
      username: ENC(MJX+k+uCnubICpKQeYdgRg==)
      password: ENC(JpGdXlntVs1tD+mf8k3K7PkhQE66QHQe)
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(TClqv5thiUKkbxc9fS4UENyPm4A+PjZRl0O2IL2nEi0cd8DBjxXX4IAbqaNbhuH/a2Ikuqiu3DywkCK1ua0ObgRLsRHGv2O960URQITw8zBMvNxJG+53OQ==)
      username: ENC(McklXvG3Ob3HhtLhnGs1sw==)
      password: ENC(ngmp3SyETKss5kIBAaJWb1EYUgYE8Bqh)
