spring:
  redis:
    host: ENC(QkIm4Fx0t9RNQtBYzY0/1gTlfOjYGbmA)
    port: ENC(ysB2BXToP07TTsFKCsTknw==)
    password: ENC(UJ9WdLu3WVgjLl+kBE1VMJw1SLQ2B0dX)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(0SUyw7B+cKv9VCZDbAiYmzMZNVTVmQeh4NQqck4CdcYZBiYd14BQplaUFm+xRZfRYzSKGtsaJfGQjFKPYsCswXb8/K+pwJYz+bLkmWEi410Qs+SxBmqetg==)
    username: ENC(MJX+k+uCnubICpKQeYdgRg==)
    password: ENC(JpGdXlntVs1tD+mf8k3K7PkhQE66QHQe)
