name: TopCariving Build Test ☀️

on:
  pull_request:
    branches:
      - 'dev'
    paths:
      - '**.java'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        if: startsWith(github.ref, 'refs/heads/feat/back/')
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend

      - name: Test With Gradle
        run: ./gradlew --info test -Pjasypt.password='${{ secrets.JASYPT_SECRET }}'
        working-directory: ./backend